// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateManualBackup(arg1) {
  return window['go']['main']['App']['CreateManualBackup'](arg1);
}

export function DeleteGame(arg1) {
  return window['go']['main']['App']['DeleteGame'](arg1);
}

export function ExportGameConfig(arg1) {
  return window['go']['main']['App']['ExportGameConfig'](arg1);
}

export function GetAppState() {
  return window['go']['main']['App']['GetAppState']();
}

export function ImportGameConfig() {
  return window['go']['main']['App']['ImportGameConfig']();
}

export function LaunchGame(arg1) {
  return window['go']['main']['App']['LaunchGame'](arg1);
}

export function ListBackups(arg1) {
  return window['go']['main']['App']['ListBackups'](arg1);
}

export function OpenGamePath(arg1, arg2) {
  return window['go']['main']['App']['OpenGamePath'](arg1, arg2);
}

export function PickGameExe() {
  return window['go']['main']['App']['PickGameExe']();
}

export function PickSaveDirectory() {
  return window['go']['main']['App']['PickSaveDirectory']();
}

export function RestoreBackup(arg1, arg2) {
  return window['go']['main']['App']['RestoreBackup'](arg1, arg2);
}

export function SaveGame(arg1) {
  return window['go']['main']['App']['SaveGame'](arg1);
}

export function StartSyncthing() {
  return window['go']['main']['App']['StartSyncthing']();
}

export function SyncGame(arg1, arg2) {
  return window['go']['main']['App']['SyncGame'](arg1, arg2);
}
