// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateManualBackup(arg1:string):Promise<main.BackupInfo>;

export function DeleteGame(arg1:string):Promise<main.AppState>;

export function ExportGameConfig(arg1:string):Promise<string>;

export function GetAppState():Promise<main.AppState>;

export function ImportGameConfig():Promise<main.GameConfig>;

export function LaunchGame(arg1:string):Promise<void>;

export function ListBackups(arg1:string):Promise<Array<main.BackupInfo>>;

export function OpenGamePath(arg1:string,arg2:string):Promise<void>;

export function PickGameExe():Promise<string>;

export function PickSaveDirectory():Promise<string>;

export function RestoreBackup(arg1:string,arg2:string):Promise<main.SyncResult>;

export function SaveGame(arg1:main.GameConfig):Promise<main.AppState>;

export function StartSyncthing():Promise<main.AppState>;

export function SyncGame(arg1:string,arg2:string):Promise<main.SyncResult>;
